services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-13T22-19-12Z
    command: server /data --console-address ":9001"
    ports: [ "9000:9000", "9001:9001" ]
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data

  mc:
    image: quay.io/minio/mc:RELEASE.2024-12-13T22-19-25Z
    depends_on: [ minio ]
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 admin minio123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb -p local/mlflow || true;
      /usr/bin/mc policy set public local/mlflow || true;
      tail -f /dev/null
      "

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]

  mlflow:
    image: python:3.10-slim
    depends_on: [ minio ]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-admin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-minio123}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL:-http://minio:9000}
    entrypoint: >
      sh -c "
      pip install mlflow boto3 gunicorn && 
      mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --artifacts-destination s3://mlflow
      "
    ports: [ "5001:5000" ]
    volumes:
      - mlflow-data:/mlflow

volumes:
  minio-data: {}
  mlflow-data: {}
