FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "-m", "src.fraud.train", "--data", "data/raw/PS_20174392719_1491204439457_log.csv"]
