  docker:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Build & push API (tags en minuscules)
      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ toLower(github.repository_owner) }}/mlops-fraud-detection-api:latest

      # ✅ Build & push UI (tags en minuscules)
      - name: Build & push UI
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.streamlit
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/${{ toLower(github.repository_owner) }}/mlops-fraud-detection-ui:latest
